Listen 80 
Listen 443

LoadModule authz_core_module modules/mod_authz_core.so
LoadModule ssl_module modules/mod_ssl.so
LoadModule alias_module modules/mod_alias.so
LoadModule auth_basic_module modules/mod_auth_basic.so
LoadModule authz_host_module modules/mod_authz_host.so
LoadModule authz_user_module modules/mod_authz_user.so
LoadModule authn_core_module modules/mod_authn_core.so
LoadModule authn_file_module modules/mod_authn_file.so

DocumentRoot c:/xampp/htdocs

<VirtualHost _default_:443>
   SSLEngine On
   SSLCACertificateFile c:/SSR/certificadoCA.crt
   SSLCertificateFile c:/SSR/certificadoServidor.crt
   SSLCertificateKeyFile c:/SSR/PrivadaServidor
   SSLVerifyClient require
</VirtualHost>


<VirtualHost 192.168.56.10:80>
   ServerName localhost:80
   Redirect permanent / https://192.168.56.10:443/
</VirtualHost>


<Directory "c:/xampp/htdocs">
   AuthName "Servidor SSR"
   AuthType Basic
   AuthBasicProvider file
   AuthUserFile "c:/certificados/usuarios"
   <RequireAll>
      Require user "Blas" "Carlos" "Almudena" "Dani"
      Require ip 192.168.56.0/24
   </RequireAll>
</Directory>
